#!/usr/bin/env python3

# Copyright 2018 Joseph Lorimer <joseph@lorimer.me>
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without fee is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

from re import search
from subprocess import check_output

from click import argument, command
from tabulate import tabulate


@command()
@argument('package-list')
def main(package_list):
    """Shows manually installed packages that are missing from install list.
    Accepts lists that contain one package per line in port origin format
    (e.g. www/firefox).
    """
    def clean(output):
        return output.decode('utf-8').lower().strip().split('\n')

    names = clean(check_output(['pkg', 'prime-list']))
    origins = clean(check_output(['pkg', 'prime-origins']))
    with open(package_list, encoding='utf-8') as f:
        primes = f.read()
    data = [(n, o) for (n, o) in zip(names, origins) if not search(o, primes)]
    print(tabulate(data))


if __name__ == '__main__':
    main()
